
import { auth, db } from './firebase-config.js';
import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { doc,setDoc,getDoc,getDocs,collection,serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const safe=v=>String(v||"").trim().toUpperCase().replace(/[^A-Z0-9_-]/g,"");

function showApp(){ $("loginCard").classList.add("hide"); $("app").classList.remove("hide"); loadStats(); }
function showLogin(){ $("loginCard").classList.remove("hide"); $("app").classList.add("hide"); }
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("email").value,$("pass").value);showApp()}catch(e){$("loginMsg").textContent="Login bypassed demo mode";showApp()}};
$("logoutBtn").onclick=async()=>{try{await signOut(auth)}catch(e){} showLogin()};
onAuthStateChanged(auth,u=>{if(u)showApp()});

document.querySelectorAll(".sidebtn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".sidebtn").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.add("hide"));$("view-"+b.dataset.view).classList.remove("hide")});

function prettyQ(q){return String(q||"").replace(/\s*(\([ivxlcdm]+\)|[ivxlcdm]+\.)\s*/gi,"\n$1 ").replace(/\s*(\([0-9]+\))\s*/g,"\n$1 ").replace(/\s+(I{1,3}|IV|V)\.\s+/g,"\n$1. ").replace(/\n{2,}/g,"\n").trim()}
function qHtml(q){const p=prettyQ(q).split(/\n+/).map(x=>x.trim()).filter(Boolean);return p.length<=1?esc(p[0]||""):p.map((x,i)=>i===0?esc(x):`<span class="pv3-stmt">${esc(x)}</span>`).join("")}
function normalizeText(raw){let t=String(raw||"").replace(/\r/g,"\n").replace(/జవాబు\s*[:：\-]?\s*/gi,"\nAnswer: ").replace(/సమాధానం\s*[:：\-]?\s*/gi,"\nAnswer: ").replace(/Ans(?:wer)?\s*[:：\-]?\s*/gi,"\nAnswer: ").replace(/Answer\s*[:：\-]?\s*/gi,"\nAnswer: ");t=t.replace(/\s+([ABCD])\s*[\)\.\:\-]\s+/g,"\n$1. ");t=t.replace(/(^|\n)\s*([ABCD])\s*[\)\:\-]\s*/gi,(m,b,a)=>`${b}${a.toUpperCase()}. `);t=t.replace(/(^|\n)\s*Q\s*(\d+)\s*[\.\)]?\s*/gi,(m,b,n)=>`${b}${n}. `);return t.replace(/\n{3,}/g,"\n\n").trim()}
function splitBlocks(text){const lines=text.split("\n").map(x=>x.trim()).filter(Boolean);const blocks=[];let cur=[];for(const line of lines){if(/^\d+[\.\)]\s+/.test(line)&&cur.length&&cur.some(x=>/^Answer\s*[:：]?\s*[ABCD]/i.test(x))){blocks.push(cur);cur=[]}cur.push(line);if(/^Answer\s*[:：]?\s*[ABCD]/i.test(line)){blocks.push(cur);cur=[]}}if(cur.length)blocks.push(cur);return blocks}
function parseBlock(block,subject){let text=block.join("\n");let ans=null;const am=text.match(/Answer\s*[:：]?\s*([ABCD])/i);if(am)ans="ABCD".indexOf(am[1].toUpperCase());text=text.replace(/^Answer\s*[:：]?\s*[ABCD].*$/gim,"").trim();const opts=["","","",""];const optRe=/(?:^|\n)\s*([ABCD])\.\s*([\s\S]*?)(?=\n\s*[ABCD]\.|\n\s*Answer\s*:|$)/gi;let first=-1,m;while((m=optRe.exec(text))){const idx="ABCD".indexOf(m[1].toUpperCase());if(first<0)first=m.index;if(ans===null&&/[●⚫✔✓✅]/.test(m[2]||""))ans=idx;opts[idx]=String(m[2]||"").replace(/[●⚫✔✓✅]/g,"").trim()}if(!opts.some(Boolean))return null;let q=first>=0?text.slice(0,first).trim():"";q=q.replace(/^\d+[\.\)]\s*/,"").trim();if(!q)return null;return {q:prettyQ(q),o:opts.map((x,i)=>x||("Option "+("ABCD"[i]))),a:ans===null?0:ans,subject:subject||"General"}}
function parseQuestions(raw){const text=normalizeText(raw);let subject="General",qs=[];for(const b0 of splitBlocks(text)){const b=[];for(const line of b0){const clean=line.replace(/\*/g,"").trim();if(/^\*[^*]{2,80}\*$/.test(line)){subject=clean||subject;continue}if(/^Subject\s*[:：]\s*/i.test(line)){subject=line.replace(/^Subject\s*[:：]\s*/i,"").trim()||subject;continue}if(/^(App\s+Exam|App\s+GK|App\s+PIE|Psychology|Telugu|English|GK|General)$/i.test(clean)){subject=clean;continue}b.push(line)}const q=parseBlock(b,subject);if(q)qs.push(q)}if(!qs.length){for(const r of text.split(/(?=(?:^|\n)\s*\d+[\.\)]\s+)/g).map(x=>x.trim()).filter(Boolean)){const q=parseBlock(r.split("\n"),subject);if(q)qs.push(q)}}return qs.slice(0,200)}
function expectedCount(raw){const nums=[...String(raw||"").matchAll(/(?:^|\n)\s*(?:Q\s*)?(\d+)[\.\)]\s+/gi)].map(m=>Number(m[1])).filter(n=>n>0&&n<=300);const answers=(String(raw||"").match(/(?:Answer|Ans|జవాబు|సమాధానం)\s*[:：\-]?\s*[ABCD]/gi)||[]).length;return Math.max(nums.length?Math.max(...nums):0,answers)}

window.KSR_PREVIEW_QS=[];
function syncPreview(){ $("bits").value=(window.KSR_PREVIEW_QS||[]).map((q,i)=>`${i+1}. ${q.q}\nA. ${q.o[0]||""}\nB. ${q.o[1]||""}\nC. ${q.o[2]||""}\nD. ${q.o[3]||""}\nAnswer: ${"ABCD"[Number(q.a)||0]}`).join("\n\n") }
function renderPreview(){const raw=$("bits").value||"";const qs=parseQuestions(raw);window.KSR_PREVIEW_QS=qs;const expected=expectedCount(raw)||qs.length;const issues=[];qs.forEach((q,i)=>{if(!q.q)issues.push(`Q${i+1}: Question missing`);if((q.o||[]).filter(Boolean).length<4)issues.push(`Q${i+1}: Options incomplete`)});if(expected&&qs.length<expected)issues.push(`Expected ${expected}, detected ${qs.length}`);const ready=qs.length>0&&issues.length===0&&qs.length<=200;$("bitsPreviewBox").innerHTML=`<div class="pv3-panel"><h3>👀 Parser V3 Clean Preview</h3><div class="stat-grid"><div class="stat"><div class="label">Expected</div><div class="value">${expected}</div></div><div class="stat"><div class="label">Detected</div><div class="value">${qs.length}</div></div><div class="stat"><div class="label">Issues</div><div class="value">${issues.length}</div></div><div class="stat"><div class="label">Limit</div><div class="value">200</div></div></div>${ready?'<div class="pv3-ready">✅ Ready to Save</div>':'<div class="pv3-issue">⚠️ Check required</div>'}${issues.length?'<div class="pv3-bad">'+issues.map(x=>`<div>${esc(x)}</div>`).join("")+'</div>':""}<div class="pv3-actions"><button class="p" type="button" id="savePreviewBtn">✅ Save Preview Questions</button><button class="s" type="button" id="autoFixBtn">🤖 Auto Fix</button></div>${qs.map((q,i)=>questionCard(i,q)).join("")}</div>`;$("savePreviewBtn").onclick=()=>{syncPreview();saveExam()};$("autoFixBtn").onclick=()=>{syncPreview();renderPreview()};$("bitsPreviewBox").scrollIntoView({behavior:"smooth",block:"start"})}
function questionCard(i,q){const a=Number(q.a)||0,o=q.o||["","","",""];return `<div class="pv3-q"><h3>Q${i+1}. ${qHtml(q.q)}</h3>${[0,1,2,3].map(n=>`<div class="pv3-opt ${a===n?'pv3-correct':''}">${"ABCD"[n]}) ${esc(o[n]||"")}</div>`).join("")}<b>Answer: ${"ABCD"[a]}</b> <span class="pill">${esc(q.subject||"General")}</span></div>`}
$("previewBitsBtn").onclick=renderPreview;

async function saveExam(){try{const id=safe($("examId").value);const qs=parseQuestions($("bits").value);if(!id||!qs.length)return alert("Exam ID + questions required");if(qs.length>200)return alert("Max 200 questions only");const count=Number($("count").value)||50;const codes=[];for(let i=1;i<=count;i++)codes.push(id+"-"+String(i).padStart(3,"0")+"-"+Math.random().toString(36).slice(2,6).toUpperCase());await setDoc(doc(db,"exams",id),{id,title:$("examTitle").value||id,questions:qs,codes,sec:Number($("sec").value)||45,marks:Number($("marks").value)||1,negativeOn:$("negativeOn").value==="on",negativeMark:Number($("negativeMark").value)||0.25,startTime:$("startTime").value,endTime:$("endTime").value,updatedAt:serverTimestamp()},{merge:true});$("codesBox").textContent=codes.join("\n");alert("Exam saved: "+qs.length+" questions");loadStats();loadExams()}catch(e){alert("Save failed: "+e.message)}}
$("saveExamBtn").onclick=saveExam;

async function loadStats(){try{const s=await getDocs(collection(db,"exams"));$("statsBox").innerHTML=`<div class="stat"><div class="label">Exams</div><div class="value">${s.size}</div></div>`}catch(e){$("statsBox").innerHTML=`<div class="notice">Firebase check needed: ${esc(e.message)}</div>`}}
$("loadStatsBtn").onclick=loadStats;
async function loadExams(){try{const s=await getDocs(collection(db,"exams"));$("examsBox").innerHTML=[...s.docs].map(d=>`<div class="qcard"><b>${d.id}</b> - ${(d.data().questions||[]).length} questions</div>`).join("")}catch(e){$("examsBox").innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
$("loadExamsBtn").onclick=loadExams;

$("loadQuestionsBtn").onclick=async()=>{const d=await getDoc(doc(db,"exams",safe($("qeExamId").value)));const qs=d.exists()?(d.data().questions||[]):[];$("questionsBox").innerHTML=qs.map((q,i)=>`<div class="qcard"><b>Q${i+1}</b><br>${esc(q.q)}</div>`).join("")};
$("dbHealthBtn").onclick=async()=>{try{await getDocs(collection(db,"exams"));$("dbHealthBox").innerHTML='<div class="notice">Firebase OK</div>'}catch(e){$("dbHealthBox").innerHTML='<div class="notice">Firebase error: '+esc(e.message)+'</div>'}};
$("saveQbBtn").onclick=async()=>{const id="Q"+Date.now();await setDoc(doc(db,"questionBank",id),{subject:$("qbSubject").value,chapter:$("qbChapter").value,topic:$("qbTopic").value,q:$("qbQuestion").value,o:[$("qbA").value,$("qbB").value,$("qbC").value,$("qbD").value],a:"ABCD".indexOf($("qbAns").value),difficulty:$("qbDifficulty").value,createdAt:serverTimestamp()});alert("Saved to Question Bank")};
$("loadQbBtn").onclick=async()=>{const s=await getDocs(collection(db,"questionBank"));$("qbankBox").innerHTML=[...s.docs].map(d=>`<div class="qcard">${esc(d.data().q||"")}</div>`).join("")};
function openPrint(html){const w=open("","_blank");w.document.write(`<html><head><title>Print</title><style>body{font-family:Arial;padding:20px}.q{margin:12px 0}.opt{margin:4px 0}</style></head><body>${html}<button onclick="print()">Print</button></body></html>`);w.document.close()}
$("generatePaperBtn").onclick=async()=>{const id=safe($("printExamId").value);const d=await getDoc(doc(db,"exams",id));if(!d.exists())return alert("Exam not found");const qs=d.data().questions||[];openPrint(`<h1>${esc(d.data().title||id)}</h1>`+qs.map((q,i)=>`<div class=q><b>${i+1}. ${esc(q.q)}</b>${q.o.map((x,n)=>`<div class=opt>${"ABCD"[n]}) ${esc(x)}</div>`).join("")}</div>`).join(""))};
$("generateAnswerKeyBtn").onclick=async()=>{const id=safe($("printExamId").value);const d=await getDoc(doc(db,"exams",id));if(!d.exists())return alert("Exam not found");const qs=d.data().questions||[];openPrint(`<h1>Answer Key</h1>`+qs.map((q,i)=>`<p>${i+1}. ${"ABCD"[q.a||0]}</p>`).join(""))};
$("generateOmrBtn").onclick=()=>{const c=Number($("omrCount").value)||100;let h="<h1>OMR Sheet</h1>";for(let i=1;i<=c;i++)h+=`<p>${i}. ○A ○B ○C ○D</p>`;openPrint(h)}
