import { db } from './firebase-config.js';
import { doc,getDoc,setDoc,serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js';

const $=id=>document.getElementById(id);
let EXAM=null,Q=[],cur=0,ans=[],rev=[],sec=0,timer=null,student="",phone="",eid="",code="",submitted=false,startMs=0,started=false;
function shuf(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function tick(){let m=Math.floor(sec/60),s=sec%60;$("timer").textContent=String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}
function msg(t,b=false){$("loginMsg").innerHTML=b?`<span class="bad">${t}</span>`:`<span class="ok">${t}</span>`}
document.addEventListener("DOMContentLoaded",()=>{$("startBtn").onclick=startExam;$("hallBtn").onclick=hallTicket;$("nextBtn").onclick=()=>{if(cur<Q.length-1){cur++;show()}};$("prevBtn").onclick=()=>{if(cur>0){cur--;show()}};$("markBtn").onclick=()=>{rev[cur]=!rev[cur];palette()};$("submitBtn").onclick=()=>submit(false)});
async function startExam(){try{student=$("stName").value.trim();phone=$("stPhone").value.trim();eid=$("stExamId").value.trim().toUpperCase();code=$("stCode").value.trim().toUpperCase();if(!student||!phone||!eid||!code)return msg("All fields required",true);const ex=await getDoc(doc(db,"exams",eid));if(!ex.exists())return msg("Invalid Exam ID",true);EXAM=ex.data();let n=new Date();if(EXAM.startTime&&n<new Date(EXAM.startTime))return msg("Exam not started yet",true);if(EXAM.endTime&&n>new Date(EXAM.endTime))return msg("Exam time is over",true);const cd=await getDoc(doc(db,"exams",eid,"codes",code));if(!cd.exists())return msg("Invalid code",true);if(cd.data().used)return msg("Code already used",true);if(!EXAM.questions?.length)return msg("No questions found",true);await setDoc(doc(db,"students",phone),{name:student,phone,updatedAt:serverTimestamp()},{merge:true});Q=JSON.parse(JSON.stringify(EXAM.questions)).map((q,qi)=>({originalIndex:qi,q:q.q,subject:q.subject,o:(q.o||[]).map((x,i)=>({text:x,correct:i===Number(q.a)}))}));shuf(Q);Q.forEach(q=>shuf(q.o));ans=Array(Q.length).fill(null);rev=Array(Q.length).fill(false);let normal=Q.length*(Number(EXAM.sec)||45),left=EXAM.endTime?Math.max(1,Math.floor((new Date(EXAM.endTime)-n)/1000)):normal;sec=Math.min(normal,left);startMs=Date.now();$("examTitle").textContent=EXAM.title||eid;$("login").classList.add("hide");$("exam").classList.remove("hide");started=true;show();tick();timer=setInterval(()=>{sec--;tick();if(sec<=0)submit(true)},1000)}catch(e){alert("Start failed: "+e.message)}}
function show(){let q=Q[cur],h=`<div class="q">${cur+1}. ${q.q}</div>`;q.o.forEach((o,i)=>h+=`<label class="opt"><input type="radio" name="op" ${ans[cur]===i?"checked":""} onchange="window.selectOption(${i})"> ${String.fromCharCode(65+i)}) ${o.text}</label>`);$("qcard").innerHTML=h;$("prog").textContent=`Question ${cur+1} of ${Q.length}`;palette()}
window.selectOption=i=>{ans[cur]=i;palette()};window.gotoQ=i=>{cur=i;show()};
function palette(){let h="";for(let i=0;i<Q.length;i++)h+=`<div class="num ${ans[i]!==null?"ans ":""}${rev[i]?"rev ":""}${i===cur?"cur":""}" onclick="window.gotoQ(${i})">${i+1}</div>`;$("palette").innerHTML=h}
async function submit(auto){if(submitted)return;if(!auto&&!confirm("Submit exam?"))return;submitted=true;if(timer)clearInterval(timer);try{let correct=0,wrong=0,skipped=0,details=[];Q.forEach((q,i)=>{let selected=ans[i]!==null?q.o[ans[i]]:null,corr=q.o.find(x=>x.correct),status="skipped";if(!selected)skipped++;else if(selected.correct){correct++;status="correct"}else{wrong++;status="wrong"}details.push({question:q.q,selectedText:selected?selected.text:"",correctText:corr?corr.text:"",isCorrect:status==="correct",status})});let marks=Number(EXAM.marks)||1,neg=EXAM.negativeOn?(Number(EXAM.negativeMark)||0):0,total=Q.length*marks,negativeDeducted=wrong*neg,score=correct*marks-negativeDeducted;if(score<0)score=0;let pct=total?Math.round((score/total)*10000)/100:0;await setDoc(doc(db,"exams",eid,"attempts",code),{name:student,phone,code,score,total,pct:pct+"%",correct,wrong,skipped,negativeDeducted,timeTakenSec:Math.floor((Date.now()-startMs)/1000),answerDetails:details,submittedAt:serverTimestamp()});await setDoc(doc(db,"exams",eid,"codes",code),{used:true,studentName:student,phone,usedAt:serverTimestamp()},{merge:true});$("exam").classList.add("hide");$("result").classList.remove("hide");$("result").innerHTML=`<h2>Submitted Successfully</h2><p>Score: <b>${score}/${total}</b></p><p>Percentage: <b>${pct}%</b></p><p>Correct: ${correct} | Wrong: ${wrong} | Skipped: ${skipped}</p><p>Negative Deducted: ${negativeDeducted}</p>`+details.map((r,i)=>`<div class="review-card ${r.status}"><b>Q${i+1}. ${r.question}</b><br>Your: ${r.selectedText||"Skipped"}<br>Correct: ${r.correctText}</div>`).join("")}catch(e){submitted=false;alert("Submit failed: "+e.message)}}
async function hallTicket(){let name=$("stName").value.trim()||"Student",ph=$("stPhone").value.trim()||"-",photo=$("stPhoto").value.trim(),exId=$("stExamId").value.trim().toUpperCase()||"-",exCode=$("stCode").value.trim().toUpperCase()||"-",title="-",st="-",en="-",dur="-";try{let ex=await getDoc(doc(db,"exams",exId));if(ex.exists()){let e=ex.data();title=e.title||exId;if(e.startTime)st=new Date(e.startTime).toLocaleString();if(e.endTime)en=new Date(e.endTime).toLocaleString();if(e.startTime&&e.endTime)dur=Math.round((new Date(e.endTime)-new Date(e.startTime))/60000)+" minutes"}}catch(e){}let vid="KSR-VFY-"+exId+"-"+(ph.replace(/\D/g,"").slice(-4)||"0000")+"-"+Date.now().toString().slice(-6),hall="KSR-"+exId+"-"+(ph.replace(/\D/g,"").slice(-4)||"0000")+"-"+Date.now().toString().slice(-5),qr="https://api.qrserver.com/v1/create-qr-code/?size=170x170&data="+encodeURIComponent(`KSR Hall Ticket\nName:${name}\nPhone:${ph}\nExam:${exId}\nCode:${exCode}\nVerify:${vid}`),photoHtml=photo?`<img src="${photo}" style="width:110px;height:130px;object-fit:cover;border:2px solid #0b57d0;border-radius:10px">`:`<div style="width:110px;height:130px;border:2px dashed #999;border-radius:10px;display:flex;align-items:center;justify-content:center;font-weight:900">PHOTO</div>`;let w=open("","_blank");w.document.write(`<!DOCTYPE html><html><head><title>Hall Ticket</title><style>body{font-family:Arial;background:#eef2f7}.t{max-width:820px;margin:20px auto;background:white;border:2px solid #0b57d0;border-radius:18px;overflow:hidden}.h{background:#0b57d0;color:white;text-align:center;padding:20px}.b{padding:22px}.top{display:flex;justify-content:space-between}.g{display:grid;grid-template-columns:1fr 1fr;gap:12px}.box{border:1px solid #ddd;border-radius:12px;padding:12px}.l{font-size:11px;font-weight:900;color:#555}.v{font-size:18px;font-weight:900}@media print{button{display:none}}</style></head><body><div class="t"><div class="h"><h1>KSR Online Exam Platform</h1><p>Hall Ticket QR</p></div><div class="b"><div class="top">${photoHtml}<div><img src="${qr}"><br><b>Scan to Verify</b></div></div><div class="g">${[['Hall Ticket No',hall],['Verification ID',vid],['Student Name',name],['Phone',ph],['Exam Title',title],['Exam ID',exId],['Exam Code',exCode],['Start Time',st],['End Time',en],['Duration',dur],['Status','Eligible']].map(x=>`<div class="box"><div class="l">${x[0]}</div><div class="v">${x[1]}</div></div>`).join("")}</div><p><b>Instructions:</b><br>1. Carry hall ticket.<br>2. Do not refresh during exam.<br>3. Submit before time ends.</p><br><br>Student Signature __________________ &nbsp;&nbsp; Invigilator Signature __________________</div></div><center><button onclick="print()">Print / Save PDF</button></center></body></html>`);w.document.close()}
window.addEventListener("beforeunload",e=>{if(started&&!submitted){e.preventDefault();e.returnValue="Exam running"}});


// L5.0 SPRINT-1 SECURE EXAM ENGINE
let KSR_VIOLATIONS=0, KSR_AUTOSAVE_TIMER=null, KSR_SECURE_READY=false;
function ksrSessionKey(){return (eid||"EXAM")+"_"+(code||"CODE")}
function ksrLocalKey(){return "KSR_SESSION_"+ksrSessionKey()}
function ksrData(status="running"){return {examId:eid,code,name:student,phone,answers:ans,review:rev,currentQuestion:cur,remainingTime:sec,totalQuestions:Q.length,progress:Q.length?Math.round((ans.filter(x=>x!==null).length/Q.length)*100):0,violations:KSR_VIOLATIONS,status,updatedAt:new Date().toISOString()}}
function ksrSaveLocal(){try{localStorage.setItem(ksrLocalKey(),JSON.stringify(ksrData()))}catch(e){}}
async function ksrSaveFirebase(status="running"){try{if(!eid||!code)return;await setDoc(doc(db,"exams",eid,"sessions",code),{...ksrData(status),lastSavedAt:serverTimestamp()},{merge:true});let el=document.getElementById("autosaveStatus");if(el)el.innerHTML='<span class="autosave-ok">Saved</span>'}catch(e){let el=document.getElementById("autosaveStatus");if(el)el.innerHTML='<span class="autosave-warn">Local saved</span>'}}
async function ksrAutoSave(status="running"){ksrSaveLocal();await ksrSaveFirebase(status)}
async function ksrTryResume(){try{let data=null;const s=await getDoc(doc(db,"exams",eid,"sessions",code));if(s.exists())data=s.data();if(!data){const l=localStorage.getItem(ksrLocalKey());if(l)data=JSON.parse(l)}if(data&&data.status==="running"&&Array.isArray(data.answers)&&confirm("Saved session found. Resume?")){ans=data.answers;rev=data.review||Array(Q.length).fill(false);cur=Number(data.currentQuestion)||0;sec=Number(data.remainingTime)||sec;KSR_VIOLATIONS=Number(data.violations)||0;return true}}catch(e){}return false}
function ksrSecureBar(){if(document.getElementById("secureBar"))return;const bar=document.createElement("div");bar.id="secureBar";bar.className="secure-bar";bar.innerHTML='🔒 Secure Exam Active | Auto Save: <span id="autosaveStatus">Starting...</span> | Violations: <span id="violationCount">0</span>';const ex=document.getElementById("exam");if(ex)ex.insertBefore(bar,ex.firstChild)}
async function ksrViolation(type){try{KSR_VIOLATIONS++;let v=document.getElementById("violationCount");if(v)v.textContent=String(KSR_VIOLATIONS);await setDoc(doc(db,"exams",eid,"sessions",code),{violations:KSR_VIOLATIONS,lastViolation:type,status:"running",violationUpdatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,"exams",eid,"violations",code+"_"+Date.now()),{code,phone,name:student,type,question:cur+1,at:serverTimestamp()})}catch(e){}}
function ksrInstallSecurity(){if(KSR_SECURE_READY)return;KSR_SECURE_READY=true;document.addEventListener("visibilitychange",()=>{if(document.hidden&&started&&!submitted)ksrViolation("TAB_SWITCH")});window.addEventListener("blur",()=>{if(started&&!submitted)ksrViolation("WINDOW_BLUR")});document.addEventListener("contextmenu",e=>{if(started&&!submitted){e.preventDefault();ksrViolation("RIGHT_CLICK")}});["copy","paste","cut"].forEach(ev=>document.addEventListener(ev,e=>{if(started&&!submitted){e.preventDefault();ksrViolation(ev.toUpperCase())}}))}
async function ksrStartAutosave(){ksrSecureBar();ksrInstallSecurity();await ksrAutoSave("running");if(KSR_AUTOSAVE_TIMER)clearInterval(KSR_AUTOSAVE_TIMER);KSR_AUTOSAVE_TIMER=setInterval(()=>{if(started&&!submitted)ksrAutoSave("running")},5000)}
const __ksrOldSelect=window.selectOption;window.selectOption=function(i){if(typeof __ksrOldSelect==="function")__ksrOldSelect(i);else{ans[cur]=i;if(typeof palette==="function")palette()}ksrAutoSave("running")}
const __ksrOldGoto=window.gotoQ;window.gotoQ=function(i){if(typeof __ksrOldGoto==="function")__ksrOldGoto(i);else{cur=i;show()}ksrAutoSave("running")}
const __ksrOldStart=startExam;startExam=async function(){await __ksrOldStart();if(started&&!submitted){await ksrTryResume();ksrSecureBar();show();tick();await ksrStartAutosave()}}
const __ksrOldSubmit=submit;submit=async function(auto){await ksrAutoSave(auto?"timeout_submitting":"submitting");await __ksrOldSubmit(auto);if(submitted){await ksrAutoSave("submitted");try{localStorage.removeItem(ksrLocalKey())}catch(e){}}}
